### ISSUE TITLE
Included WP Session Manager library security vulnerability

### ISSUE THREAD

**Issue by jr00ck** [jr00ck/hide-wp-toolbar#2]
The older WP Session Manager library used in this plugin has a security vulnerability. 

Possible ways to fix (chose _one_):

**Option one**
Delete the WP Session Manger code to no longer package this library within the plugin and require that the WP Session Manager plugin is installed and active independently.

**Option two**
Update the included library to the latest version of the WP Session Manager plugin.

**Option three**
Remove the dependency on WP Session Manager altogether and instead just use a transient or cookie.

I prefer option 3, as it's probably more than good enough for purposes of this plugin.

**Comment by attritionorg** [comment]
@jr00ck Do you have a reference to which WP session manager vuln that is?

**Comment by jr00ck** [comment]
@attritionorg I don't know what the vulnerability was. I just got an email from WordPress.org that the plugin was updated for a security issue and they discovered that my plugin had the vulnerable code included within it. I solved this by removing WP Session Manager from my plugin altogether and it's not longer used.
